# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a40d7e32efe0415f945b61678ffca1b10d5e4f0397d0f43e8c377f38ad5c89be31546e7a5e38e0cf6d7d14954674697a98352aa0dd6bf7496fa1169822b7b861

test:
  secret_key_base: e39b0fb57a81a3056ced18a447509639022bd5d58666533495f78e502ece5615c21d26beee122229fe98dece5ceb0ee576bf858a1ed4edf3e9d1744de1432f66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
